apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows dave to read secrets in the development namespace
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: kubernetes-dashboard #This only grants permission within the development namespace
subjects:
- kind: ServiceAccount
  name: priya #Name is case sensitive
#  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole #This must be Role or ClusterRole
  name: secret-reader #This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
